@extends('master.app')
@section('content')
@stop

<hr class="featurette-divider">
<div class="row featurette">
    <div class="col-md-12">
        <img class="featurette-image img-responsive center-block" src="images/logo.png" alt="logo.png">
    </div>
</div>

<hr class="featurette-divider">
<p>ABOUT USA
    <br>
Acceptance Test Technician is a process of testing lighting controls to see if they are in compliance with Title 24 Part 6 Mandatory Lighting Controls.

In November 2014 NLCAA, Inc. was approved by the California Energy Commission as Acceptance Test Technician Certified Provider.

The NLCAA mission is to fill the growing need in the Energy Efficiency industry for a technically superior, yet customer-oriented
    as an Acceptance Test Certified Provider.
<hr class="featurette-divider">
<div class="row featurette">
    <div class="col-md-12">
        <img class="featurette-image img-responsive center-block" src="images/logoabout.png" alt="logo.png">
    </div>
</div>
<p>NLCAA, Inc. is a non-profit organization that provides service, support, training and certification to Acceptance Test Technicians,
    and Acceptance Test Contractors. NLCAA supports the construction industry by providing Advocates to review the proposed
    “New Energy Standards”. Having influence in the Energy Standards Building Code prior to law, will keep the construction industry
    informed as to the financial impact the new law will have on their construction projects. Your membership pays for supporting our
    Advocates. Acceptance Test Technician was proposed in 2008 and now is officially required and still the construction industry is
    ill equipped on how to implement the 2013 Energy Standards.

     Acceptance Test Technician has extensive training in lighting controls to have the ability to review lighting controls that must comply
    with Title 24 Part 6 mandatory.
</p>
Acceptance Test Software
<p>
NLCAA, Inc. has developed and owns its own software that resides in our cloud which has been reviewed by the California Energy Commission Staff.
<ul>
<li>The software is utilized by the Acceptance Test Technician to enter testing data with a IPAD, tablet, and or smart phone.</li>
    <li>All required forms are generated by the software.</li>
    <li>The required test calculations are embedded in the software to eliminate mathematical errors.</li>
    <li>The software provides taking pictures of the devices tested for quality assurance.</li>
    <li>Required signatures for the Declaration Form will be entered by using a stylus from any location.</li>
    <li>Certificates of Acceptance will be automatically email to building inspector provided that you enter their email address.</li>
NLCAA, Inc. maintains the computer based registry of data as a repository of information for the required 3 years that can be accessed by the ATTs, building departments, contractors and government agencies.
You may print out all the forms.</p></ul>
